Repository DIT112-V21/group-09, pull requests merged in 2021-05, with the labels that each got.

#71 Calculate mission distance
  arduino/smartcar/Mission.cpp
  arduino/smartcar/Mission.h
  arduino/smartcar/smartcar.ino
Labels: C++, sprint-2, test

#72 Update communication.js
  frontendApp/assets/js/communication.js
Labels: JS, M2, NodeJS, mqtt, sprint-2

#80 Clean up files
  arduino/smartcar/smartcar.ino
  frontendApp/assets/css/style.css
Labels: CSS, M2, sprint-2

#81 Implement live feed
  arduino/smartcar/secrets.hpp
  arduino/smartcar/smartcar.ino
  frontendApp/assets/js/communication.js
  frontendApp/manual.html
Labels: C++, CSS, JS, M2, NodeJS, mqtt, sprint-2

#82 Implement camera snapshot
  frontendApp/assets/js/communication.js
  frontendApp/manual.html
Labels: JS, M2, sprint-2

#84 Implement manual control
  frontendApp/assets/css/mqtt.css
  frontendApp/assets/css/style.css
  frontendApp/assets/images/kaktos.jpg
  frontendApp/assets/images/kisspng-computer-icons-drop-down-list-menu-arrow-computer-5afb9d32be3ba5.9657372715264392187792.png
  frontendApp/assets/images/marsAnimation.gif
  frontendApp/assets/js/renderer.js
  frontendApp/help.html
  frontendApp/index.html
  frontendApp/manual.html
  frontendApp/mission.html
  frontendApp/mqtt.html
  frontendApp/settings.html
Labels: CSS, JS, M2, NodeJS, project

#86 Update mission.js
  frontendApp/assets/js/mission.js
Labels: JS

#91 Update README.md
  README.md
Labels: M6, assignment, documentation, enhancement, project, sprint-3

#95 Connect database with the frontend app
  frontendApp/assets/js/db_connection.js
  frontendApp/package-lock.json
  frontendApp/package.json
Labels: JS, M3, NodeJS, database, sprint-3, test

#97 Implement changelog workflow
  .github/workflows/changelog-generator.yml
Labels: M7, documentation, enhancement, project, sprint-3

#98 Update changelog generator
  .github/workflows/changelog-generator.yml
  CHANGELOG.md
Labels: M7, documentation, enhancement, project, sprint-3

#99 Update changelog-generator.yml
  .github/workflows/changelog-generator.yml
Labels: M7, enhancement, project

#103 Add user Input into an array
  frontendApp/assets/js/mission.js
  frontendApp/mission.html
Labels: JS, M4, high-priority, sprint-3

#108 Add QR Code Feature
  frontendApp/assets/js/communication.js
  frontendApp/assets/js/qr-scanner-worker.min.js
  frontendApp/assets/js/qr-scanner-worker.min.js.map
  frontendApp/assets/js/qr-scanner.umd.min.js
  frontendApp/assets/js/qr-scanner.umd.min.js.map
  frontendApp/manual.html
Labels: JS, M4, high-priority, sprint-3

#114 Implement mission templates
  frontendApp/assets/css/style.css
  frontendApp/assets/css/typography.css
  frontendApp/assets/images/map-plot-midpoint.png
  frontendApp/assets/images/map-plot-waypoint.png
  frontendApp/assets/js/leaflet-mission-polyline.js
  frontendApp/assets/js/map.js
  frontendApp/mission.html
Labels: CSS, JS, M4, NodeJS, sprint-3

#104 Add Setup Guides
  frontendApp/assets/css/style.css
  frontendApp/assets/images/Control-Pad.png
  frontendApp/assets/images/Manual-Control-Live-Streaming.png
  frontendApp/assets/images/Manual-Control-Serial-Feed.png
  frontendApp/assets/images/Manual-Control-Telemetry.png
  frontendApp/assets/images/Manual-Control-Terminal.png
  frontendApp/assets/images/Manual-Control.png
  frontendApp/help.html
Labels: JS, M6, documentation, sprint-3

#115 Implement settings page
  frontendApp/assets/css/style.css
  frontendApp/assets/css/typography.css
  frontendApp/assets/images/manual-streams.png
  frontendApp/assets/js/communication.js
  frontendApp/assets/js/jsQR.js
  frontendApp/assets/js/mission.js
  frontendApp/assets/js/settings-old.js
  frontendApp/assets/js/settings.js
  frontendApp/config/dbconfig.json
  frontendApp/config/default.json
  frontendApp/help.html
  frontendApp/models/Missions.js
  frontendApp/models/Mqtt.js
  frontendApp/models/User.js
  frontendApp/models/topics.js
  frontendApp/package-lock.json
  frontendApp/package.json
  frontendApp/pages/manual_setting.html
  frontendApp/pages/mission_setting.html
  frontendApp/pages/mqtt_setting.html
  frontendApp/pages/rover_setting.html
  frontendApp/pages/table.html
  frontendApp/pages/table.js
  frontendApp/settings.html
Labels: JS, M8, NodeJS, database, mqtt, sprint-4

#116 User registration and login
  frontendApp/assets/css/notifications.css
  frontendApp/assets/css/style.css
  frontendApp/assets/css/user-profile.css
  frontendApp/assets/images/checked-valid.png
  frontendApp/assets/images/close-toast.png
  frontendApp/assets/images/unchecked-invalid.png
  frontendApp/assets/js/user.js
  frontendApp/config/db-init.sql
  frontendApp/index.html
  frontendApp/main.js
  frontendApp/manual.html
  frontendApp/package-lock.json
  frontendApp/package.json
Labels: CSS, JS, M8, NodeJS, database, enhancement, high-priority, sprint-4

#117 Implement bugfixes
  README.md
  frontendApp/assets/css/style.css
  frontendApp/assets/css/typography.css
  frontendApp/assets/images/close-toast.svg
  frontendApp/assets/js/communication.js
  frontendApp/assets/js/map.js
  frontendApp/assets/js/mission.js
  frontendApp/assets/js/settings.js
  frontendApp/assets/js/user.js
  frontendApp/help.html
  frontendApp/index.html
  frontendApp/manual.html
  frontendApp/mission.html
  frontendApp/settings.html
Labels: CSS, JS, M7, bug

#118 Implement restore session
  frontendApp/assets/js/user.js
  frontendApp/main.js
  frontendApp/manual.html
  frontendApp/mission.html
  frontendApp/package-lock.json
  frontendApp/package.json
  frontendApp/settings.html
Labels: JS, M3, NodeJS, sprint-4

#119 Implement mission control
  arduino/missionControl/missionControl.ino
  arduino/missionControl/secrets.hpp
  arduino/smartcar/Mission.cpp
  arduino/smartcar/Mission.h
Labels: C++, M5, sprint-4

#121 Implement Mission save, load
  frontendApp/assets/css/mission.css
  frontendApp/assets/css/style.css
  frontendApp/assets/css/typography.css
  frontendApp/assets/js/map.js
  frontendApp/assets/js/mission.js
  frontendApp/assets/js/user.js
  frontendApp/mission.html
Labels: CSS, JS, M3, NodeJS, database, enhancement, high-priority, sprint-4

#122 Implement mission tracking
  frontendApp/assets/css/mission.css
  frontendApp/assets/css/style.css
  frontendApp/assets/css/typography.css
  frontendApp/assets/js/communication.js
  frontendApp/assets/js/jsQR.js
  frontendApp/assets/js/map.js
  frontendApp/assets/js/mission.js
  frontendApp/assets/js/missionControl.js
  frontendApp/assets/js/settings-old.js
  frontendApp/manual.html
  frontendApp/mission.html
  frontendApp/models/Missions.js
  frontendApp/models/Mqtt.js
  frontendApp/models/User.js
  frontendApp/models/topics.js
  frontendApp/pages/manual_setting.html
  frontendApp/pages/mqtt_setting.html
  frontendApp/pages/rover_setting.html
Labels: CSS, JS, M4, database, high-priority, mqtt, sprint-4

#123 Implement beta release build
  .github/workflows/changelog-generator.yml
  .github/workflows/electron-build.yml
  .github/workflows/electron-ci.yml
  CHANGELOG.md
  frontendApp/assets/css/mission.css
  frontendApp/assets/css/user-profile.css
  frontendApp/assets/js/communication.js
  frontendApp/assets/js/db_connection.js
  frontendApp/assets/js/map.js
  frontendApp/assets/js/mission.js
  frontendApp/assets/js/missionControl.js
  frontendApp/assets/js/settings.js
  frontendApp/assets/js/user.js
  frontendApp/build/icon.png
  frontendApp/config/config.json
  frontendApp/config/dbconfig.json
  frontendApp/config/default.json
  frontendApp/main.js
  frontendApp/mission.html
  frontendApp/package-lock.json
  frontendApp/package.json
  frontendApp/settings.html
  frontendApp/yarn.lock
Labels: M6, enhancement, high-priority, project, sprint-4

#127 Update release build
  .github/workflows/arduino-build.yml
  CHANGELOG.md
  README.md
  frontendApp/assets/js/communication.js
  frontendApp/assets/js/missionControl.js
  frontendApp/assets/js/settings.js
  frontendApp/assets/js/user.js
  frontendApp/main.js
  frontendApp/manual.html
  frontendApp/mission.html
  frontendApp/package.json
Labels: M6, bug, database, high-priority, mqtt, project, sprint-4

#129 Update map heading conversion
  frontendApp/assets/js/map.js
  frontendApp/assets/js/mission.js
  frontendApp/assets/js/missionControl.js
Labels: JS, M4, bug

#130 Drive mission steps
  .github/workflows/arduino-build.yml
  arduino/missionControl/missionControl.ino
Labels: C++, M4, high-priority

#131 Release first v1.0.0 version
  CHANGELOG.md
  README.md
  frontendApp/assets/js/map.js
  frontendApp/assets/js/missionControl.js
Labels: M6, enhancement, high-priority, project, sprint-4
